/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package donpedromz.integracion_prolog.ui;

import donpedromz.integracion_prolog.controllers.SpecialistController;
import donpedromz.integracion_prolog.entities.Disease;
import donpedromz.integracion_prolog.entities.Diagnostic;
import donpedromz.integracion_prolog.entities.Recomendation;
import donpedromz.integracion_prolog.entities.Symptom;
import java.util.List;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juanp
 */
public class ConsultPatientDiagnoseFrame extends javax.swing.JFrame {

    private SpecialistController controller;

    /**
     * Creates new form ConsultPatientDiagnoseFrame
     */
    public ConsultPatientDiagnoseFrame(SpecialistController controller) {
        this.controller = controller;
        initComponents();
        configUi();
    }

    private void configUi() {
        setLocationRelativeTo(null);
        setResizable(false);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        resetTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        ageField = new javax.swing.JTextField();
        searchButton = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("INGRESAR EDAD");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        ageField.setBorder(null);
        jPanel2.add(ageField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 325, 38));

        searchButton.setBackground(new java.awt.Color(255, 51, 51));
        searchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
        });
        searchButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/donpedromz/integracion_prolog/assets/icons/filtrar_icono.png"))); // NOI18N
        searchButton.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 140));

        jPanel2.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 130, 140));

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("INGRESAR NOMBRE");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        nameField.setBorder(null);
        jPanel2.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 325, 38));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 590));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 720, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
        if (this.controller != null) {
            this.controller.handleConsultSearchClicked();
        }
    }//GEN-LAST:event_searchButtonMouseClicked

    public JTextField getNameField() {
        return nameField;
    }

    public JTextField getAgeField() {
        return ageField;
    }

    public JTable getResultsTable() {
        return jTable1;
    }

    public void loadDiagnostics(List<Diagnostic> diagnostics) {
        resetTable();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        for (Diagnostic diagnostic : diagnostics) {
            List<Disease> diseases = diagnostic.getDiseases();
            if (diseases == null || diseases.isEmpty()) {
                model.addRow(new Object[]{
                    diagnostic.getId(),
                    null,
                    "",
                    "",
                    "",
                    ""
                });
                continue;
            }

            for (Disease disease : diseases) {
                String symptoms = joinSymptoms(disease != null ? disease.getSymptoms() : null);
                String recs = joinRecs(disease != null ? disease.getRecomendations() : null);
                model.addRow(new Object[]{
                    diagnostic.getId(),
                    disease != null ? disease.getId() : null,
                    disease != null ? disease.getName() : "",
                    (disease != null && disease.getCategory() != null) ? disease.getCategory().getName() : "",
                    symptoms,
                    recs
                });
            }
        }
    }

    public void clearTable() {
        resetTable();
    }

    private void resetTable() {
        jTable1.setModel(new DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Id Diagnostico", "Id Enfermedad", "Enfermedad", "Categoria", "Sintomas", "Recomendaciones"
            }
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
    }

    private String joinSymptoms(List<Symptom> symptoms) {
        if (symptoms == null) {
            return "";
        }
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < symptoms.size(); i++) {
            Symptom symptom = symptoms.get(i);
            String value = symptom != null ? symptom.getDescription() : "";
            sb.append(value);
            if (i < symptoms.size() - 1) {
                sb.append(", ");
            }
        }
        return sb.toString();
    }

    private String joinRecs(List<Recomendation> recs) {
        if (recs == null) {
            return "";
        }
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < recs.size(); i++) {
            Recomendation rec = recs.get(i);
            String value = rec != null ? rec.getDescription() : "";
            sb.append(value);
            if (i < recs.size() - 1) {
                sb.append(", ");
            }
        }
        return sb.toString();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nameField;
    private javax.swing.JPanel searchButton;
    // End of variables declaration//GEN-END:variables
}
