/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package donpedromz.integracion_prolog.ui;

import donpedromz.integracion_prolog.controllers.SpecialistController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author milomnz
 */
public class CreateDisease extends javax.swing.JPanel {

    private transient SpecialistController controller;

    /**
     * Creates new form CreeateDisease
     */
    public CreateDisease(SpecialistController controller) {
        this.controller = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelIzq = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Imagen = new javax.swing.JLabel();
        GuardarEnfermedad = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Volver = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        LabelSympton5 = new javax.swing.JLabel();
        LabelSympton6 = new javax.swing.JLabel();
        categoryField = new javax.swing.JTextField();
        PanelDer = new javax.swing.JPanel();
        LabelSympton1 = new javax.swing.JLabel();
        LabelSympton2 = new javax.swing.JLabel();
        LabelSympton3 = new javax.swing.JLabel();
        LabelSympton4 = new javax.swing.JLabel();
        sint1Field = new javax.swing.JTextField();
        sint2Field = new javax.swing.JTextField();
        sint4Field = new javax.swing.JTextField();
        sint3Field = new javax.swing.JTextField();
        LabelRecommendations = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        recomendationsArea = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelIzq.setBackground(new java.awt.Color(255, 255, 255));

        Title.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        Title.setForeground(new java.awt.Color(0, 0, 0));
        Title.setText("REGISTRO DE NUEVAS ENFERMEDADES");

        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/donpedromz/integracion_prolog/assets/icons/disease-prevention.png"))); // NOI18N
        Imagen.setToolTipText("");

        GuardarEnfermedad.setBackground(new java.awt.Color(153, 204, 255));
        GuardarEnfermedad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarEnfermedadMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel3.setText("GUARDAR ENFERMEDAD");

        javax.swing.GroupLayout GuardarEnfermedadLayout = new javax.swing.GroupLayout(GuardarEnfermedad);
        GuardarEnfermedad.setLayout(GuardarEnfermedadLayout);
        GuardarEnfermedadLayout.setHorizontalGroup(
            GuardarEnfermedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GuardarEnfermedadLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel3)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        GuardarEnfermedadLayout.setVerticalGroup(
            GuardarEnfermedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GuardarEnfermedadLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        Volver.setBackground(new java.awt.Color(255, 51, 51));
        Volver.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Volver.setToolTipText("");
        Volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VolverMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("VOLVER");

        javax.swing.GroupLayout VolverLayout = new javax.swing.GroupLayout(Volver);
        Volver.setLayout(VolverLayout);
        VolverLayout.setHorizontalGroup(
            VolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VolverLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel4)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        VolverLayout.setVerticalGroup(
            VolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VolverLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        LabelSympton5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        LabelSympton5.setForeground(new java.awt.Color(0, 0, 0));
        LabelSympton5.setText("Nombre Enfermedad");

        LabelSympton6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        LabelSympton6.setForeground(new java.awt.Color(0, 0, 0));
        LabelSympton6.setText("Categoria");

        javax.swing.GroupLayout PanelIzqLayout = new javax.swing.GroupLayout(PanelIzq);
        PanelIzq.setLayout(PanelIzqLayout);
        PanelIzqLayout.setHorizontalGroup(
            PanelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIzqLayout.createSequentialGroup()
                .addGroup(PanelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelIzqLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Title))
                    .addGroup(PanelIzqLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelIzqLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(PanelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelSympton5)
                            .addGroup(PanelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(GuardarEnfermedad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField1)
                                .addComponent(LabelSympton6)
                                .addComponent(categoryField))))
                    .addGroup(PanelIzqLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(Volver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        PanelIzqLayout.setVerticalGroup(
            PanelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIzqLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(LabelSympton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelSympton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(categoryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(GuardarEnfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Volver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        add(PanelIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 500));

        PanelDer.setBackground(new java.awt.Color(153, 204, 255));

        LabelSympton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        LabelSympton1.setText("Sintoma 1");

        LabelSympton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        LabelSympton2.setText("Sintoma 2");

        LabelSympton3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        LabelSympton3.setText("Sintoma 3");

        LabelSympton4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        LabelSympton4.setText("Sintoma 4");

        sint1Field.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N

        sint2Field.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        sint2Field.addActionListener(this::sint2FieldActionPerformed);

        sint4Field.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N

        sint3Field.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N

        LabelRecommendations.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        LabelRecommendations.setText("INGRESE EL TRATAMIENTO PARA LA ENFERMEDAD");

        recomendationsArea.setColumns(20);
        recomendationsArea.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        recomendationsArea.setRows(5);
        jScrollPane1.setViewportView(recomendationsArea);

        javax.swing.GroupLayout PanelDerLayout = new javax.swing.GroupLayout(PanelDer);
        PanelDer.setLayout(PanelDerLayout);
        PanelDerLayout.setHorizontalGroup(
            PanelDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDerLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(PanelDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(PanelDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sint4Field, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelSympton3)
                        .addComponent(LabelSympton1)
                        .addComponent(sint1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelSympton2)
                        .addComponent(sint2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sint3Field, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelSympton4))
                    .addComponent(LabelRecommendations, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        PanelDerLayout.setVerticalGroup(
            PanelDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDerLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(LabelSympton1)
                .addGap(18, 18, 18)
                .addComponent(sint1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelSympton2)
                .addGap(18, 18, 18)
                .addComponent(sint2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelSympton3)
                .addGap(18, 18, 18)
                .addComponent(sint3Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelSympton4)
                .addGap(18, 18, 18)
                .addComponent(sint4Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelRecommendations, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        add(PanelDer, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 460, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void sint2FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sint2FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sint2FieldActionPerformed

    private void GuardarEnfermedadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarEnfermedadMouseClicked
        List<String> symptoms = collectSymptoms();
        List<String> recommendations = collectRecommendations();

        try {
            this.controller.handleCreateDiseaseSave(
                    jTextField1.getText(),
                    categoryField.getText(),
                    symptoms,
                    recommendations
            );
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(
                    null,
                    ex.getMessage() != null ? ex.getMessage() : "Datos invalidos",
                    "Error de validacion",
                    JOptionPane.ERROR_MESSAGE
            );
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
                    null,
                    ex.getMessage() != null ? ex.getMessage() : "Error al registrar la enfermedad",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_GuardarEnfermedadMouseClicked

    private void VolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverMouseClicked
        SwingUtilities.getWindowAncestor(this).dispose();
        this.controller.handleReturnHome();
    }//GEN-LAST:event_VolverMouseClicked

    private List<String> collectSymptoms() {
        List<String> symptoms = new ArrayList<>();
        symptoms.add(sint1Field.getText());
        symptoms.add(sint2Field.getText());
        symptoms.add(sint3Field.getText());
        symptoms.add(sint4Field.getText());
        return symptoms;
    }

    private List<String> collectRecommendations() {
        List<String> recommendations = new ArrayList<>();
        String raw = recomendationsArea.getText();
        if (raw != null) {
            String[] parts = raw.split(",");
            for (String part : parts) {
                if (part != null && !part.trim().isEmpty()) {
                    recommendations.add(part.trim());
                }
            }
        }
        return recommendations;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GuardarEnfermedad;
    private javax.swing.JLabel Imagen;
    private javax.swing.JLabel LabelRecommendations;
    private javax.swing.JLabel LabelSympton1;
    private javax.swing.JLabel LabelSympton2;
    private javax.swing.JLabel LabelSympton3;
    private javax.swing.JLabel LabelSympton4;
    private javax.swing.JLabel LabelSympton5;
    private javax.swing.JLabel LabelSympton6;
    private javax.swing.JPanel PanelDer;
    private javax.swing.JPanel PanelIzq;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel Volver;
    private javax.swing.JTextField categoryField;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea recomendationsArea;
    private javax.swing.JTextField sint1Field;
    private javax.swing.JTextField sint2Field;
    private javax.swing.JTextField sint3Field;
    private javax.swing.JTextField sint4Field;
    // End of variables declaration//GEN-END:variables
}
