/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package donpedromz.integracion_prolog.ui;

import donpedromz.integracion_prolog.controllers.SpecialistController;
import donpedromz.integracion_prolog.entities.Diagnostic;
import donpedromz.integracion_prolog.entities.Recomendation;
import donpedromz.integracion_prolog.entities.Symptom;
import donpedromz.integracion_prolog.entities.Disease;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juanp
 */
public class DiagnosticFrame extends javax.swing.JFrame {

    private List<Symptom> inputSymptoms = new ArrayList<>();
    private List<Diagnostic> diagnostics = new ArrayList<>();
    private SpecialistController controller;

    /**
     * Creates new form DiagnosticFrame
     */
    public DiagnosticFrame(SpecialistController controller) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setResizable(false);
        this.controller = controller;
    }

    public void loadDiagnostics(List<Diagnostic> diagnostics, List<Symptom> inputSymptoms) {
        this.inputSymptoms = inputSymptoms != null ? new ArrayList<>(inputSymptoms) : new ArrayList<>();
        this.diagnostics = diagnostics != null ? new ArrayList<>(diagnostics) : new ArrayList<>();

        String[] cols = {"Id Enfermedad", "Enfermedad", "Categoria", "Sintomas", "Recomendaciones"};
        DefaultTableModel model = new DefaultTableModel(cols, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        for (Diagnostic d : diagnostics) {
            List<Disease> diseases = d.getDiseases();
            if (diseases == null || diseases.isEmpty()) {
                model.addRow(new Object[]{
                    "",
                    "",
                    "",
                    ""
                });
                continue;
            }

            for (Disease disease : diseases) {
                String sintomasEnfermedad = joinSymptoms(disease != null ? disease.getSymptoms() : null);
                String recomendaciones = joinRecs(disease != null ? disease.getRecomendations() : null);
                model.addRow(new Object[]{
                    disease != null ? disease.getId() : null,
                    disease != null ? disease.getName() : "",
                    (disease != null && disease.getCategory() != null) ? disease.getCategory().getName() : "",
                    sintomasEnfermedad,
                    recomendaciones
                });
            }
        }

        jTable1.setModel(model);
        jTable1.setRowHeight(25);
    }

    private String joinSymptoms(List<Symptom> symptoms) {
        if (symptoms == null) return "";
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < symptoms.size(); i++) {
            Symptom symptom = symptoms.get(i);
            if (symptom != null) {
                sb.append(symptom.getDescription());
            }
            if (i < symptoms.size() - 1) {
                sb.append(", ");
            }
        }
        return sb.toString();
    }

    private String joinRecs(List<Recomendation> recs) {
        if (recs == null) return "";
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < recs.size(); i++) {
            Recomendation rec = recs.get(i);
            if (rec != null) {
                sb.append(rec.getDescription());
            }
            if (i < recs.size() - 1) {
                sb.append(", ");
            }
        }
        return sb.toString();
    }

    public List<Symptom> getInputSymptoms() {
        return new ArrayList<>(inputSymptoms);
    }

    public List<Diagnostic> getDiagnostics() {
        return new ArrayList<>(diagnostics);
    }

    public javax.swing.JPanel getFilterButton() {
        return filterButton;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        filterButton = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        returnHomeButton = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        persistDataButton = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        filterButton.setBackground(new java.awt.Color(255, 51, 51));
        filterButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        filterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filterButtonMouseClicked(evt);
            }
        });
        filterButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/donpedromz/integracion_prolog/assets/icons/filtrar_icono.png"))); // NOI18N
        filterButton.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 140));

        jPanel2.add(filterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 350, 130, 140));

        returnHomeButton.setBackground(new java.awt.Color(102, 102, 255));
        returnHomeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        returnHomeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnHomeButtonMouseClicked(evt);
            }
        });
        returnHomeButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/donpedromz/integracion_prolog/assets/icons/icono_casa.png"))); // NOI18N
        returnHomeButton.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, -1, 140));

        jPanel2.add(returnHomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 130, 140));

        persistDataButton.setBackground(new java.awt.Color(0, 255, 0));
        persistDataButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        persistDataButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                persistDataButtonMouseClicked(evt);
            }
        });
        persistDataButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/donpedromz/integracion_prolog/assets/icons/confirmar_icono.png"))); // NOI18N
        persistDataButton.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 140));

        jPanel2.add(persistDataButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 130, 140));

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("POSIBLES DIAGNOSTICOS");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 70));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 930, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 926, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filterButtonMouseClicked
        if (controller != null) {
            controller.handleFilterButtonClicked();
        }
    }//GEN-LAST:event_filterButtonMouseClicked

    private void persistDataButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_persistDataButtonMouseClicked
        if (controller != null) {
            controller.handlePersistDataClicked();
        }
    }//GEN-LAST:event_persistDataButtonMouseClicked

    private void returnHomeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnHomeButtonMouseClicked
        if (controller != null) {
            controller.handleReturnHome();
        }
    }//GEN-LAST:event_returnHomeButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel filterButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel persistDataButton;
    private javax.swing.JPanel returnHomeButton;
    // End of variables declaration//GEN-END:variables
}
