/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package donpedromz.integracion_prolog.ui;

import donpedromz.integracion_prolog.controllers.SpecialistController;
import javax.swing.JPanel;

/**
 *
 * @author juanp
 */
public class EntryFrame extends javax.swing.JFrame {
    private SpecialistController controller;
    private void configUi(){
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
    /**
     * Creates new form EntryFrame
     */
    public EntryFrame(SpecialistController controller) {
        this.controller = controller;
        initComponents();
        configUi();
    }

    public JPanel getjPanel2() {
        return generateDiagnoseButton;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        createDiseaseButton = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        generateDiagnoseButton = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        consultDiagnoseButton = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        statsButton = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SISTEMA EXPERTO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/donpedromz/integracion_prolog/assets/icons/icono_lobo.png"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 300, 300));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("¡El Médico de tu Confianza!");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 570));

        createDiseaseButton.setBackground(new java.awt.Color(153, 204, 255));
        createDiseaseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createDiseaseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createDiseaseButtonMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("REPORTAR NUEVA ENFERMEDAD");

        javax.swing.GroupLayout createDiseaseButtonLayout = new javax.swing.GroupLayout(createDiseaseButton);
        createDiseaseButton.setLayout(createDiseaseButtonLayout);
        createDiseaseButtonLayout.setHorizontalGroup(
            createDiseaseButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createDiseaseButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        createDiseaseButtonLayout.setVerticalGroup(
            createDiseaseButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createDiseaseButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(createDiseaseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 340, 70));

        generateDiagnoseButton.setBackground(new java.awt.Color(153, 204, 255));
        generateDiagnoseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        generateDiagnoseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generateDiagnoseButtonMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("GENERAR DIAGNÓSTICO");

        javax.swing.GroupLayout generateDiagnoseButtonLayout = new javax.swing.GroupLayout(generateDiagnoseButton);
        generateDiagnoseButton.setLayout(generateDiagnoseButtonLayout);
        generateDiagnoseButtonLayout.setHorizontalGroup(
            generateDiagnoseButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, generateDiagnoseButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        generateDiagnoseButtonLayout.setVerticalGroup(
            generateDiagnoseButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, generateDiagnoseButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(generateDiagnoseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 340, 70));

        consultDiagnoseButton.setBackground(new java.awt.Color(153, 204, 255));
        consultDiagnoseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultDiagnoseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultDiagnoseButtonMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CONSULTAR DIAGNOSTICO");

        javax.swing.GroupLayout consultDiagnoseButtonLayout = new javax.swing.GroupLayout(consultDiagnoseButton);
        consultDiagnoseButton.setLayout(consultDiagnoseButtonLayout);
        consultDiagnoseButtonLayout.setHorizontalGroup(
            consultDiagnoseButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultDiagnoseButtonLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        consultDiagnoseButtonLayout.setVerticalGroup(
            consultDiagnoseButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultDiagnoseButtonLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bg.add(consultDiagnoseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 340, 70));

        statsButton.setBackground(new java.awt.Color(153, 204, 255));
        statsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        statsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statsButtonMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ESTADISTICAS");

        javax.swing.GroupLayout statsButtonLayout = new javax.swing.GroupLayout(statsButton);
        statsButton.setLayout(statsButtonLayout);
        statsButtonLayout.setHorizontalGroup(
            statsButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statsButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        statsButtonLayout.setVerticalGroup(
            statsButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statsButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(statsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createDiseaseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createDiseaseButtonMouseClicked
        this.controller.handleOpenCreateDisease();
    }//GEN-LAST:event_createDiseaseButtonMouseClicked

    private void generateDiagnoseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generateDiagnoseButtonMouseClicked

        this.controller.handleClick(evt);
    }//GEN-LAST:event_generateDiagnoseButtonMouseClicked

    private void consultDiagnoseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultDiagnoseButtonMouseClicked
        this.controller.handleOpenConsultDiagnose();
    }//GEN-LAST:event_consultDiagnoseButtonMouseClicked

    private void statsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statsButtonMouseClicked
        this.controller.handleOpenStats();
    }//GEN-LAST:event_statsButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel consultDiagnoseButton;
    private javax.swing.JPanel createDiseaseButton;
    private javax.swing.JPanel generateDiagnoseButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel statsButton;
    // End of variables declaration//GEN-END:variables
}
