/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package donpedromz.integracion_prolog.ui;

import donpedromz.integracion_prolog.controllers.SpecialistController;
import donpedromz.integracion_prolog.entities.Diagnostic;
import donpedromz.integracion_prolog.entities.Disease;
import donpedromz.integracion_prolog.entities.Recomendation;
import donpedromz.integracion_prolog.entities.Symptom;
import donpedromz.integracion_prolog.ui.modelEntities.SymptomModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juanp
 */
public class SymptomSelectionFrame extends javax.swing.JFrame {
    private SpecialistController controller;
    private List<SymptomModel> modeledSymptoms;
    private List<Diagnostic> currentDiagnostics = new ArrayList<>();
    private List<Symptom> currentInputSymptoms = new ArrayList<>();
    private void initSymptomModel(List<Symptom> symptoms) {
        List<SymptomModel> model = new ArrayList<>();
        for (Symptom s : symptoms) {
            model.add(new SymptomModel(s));
        }
        this.modeledSymptoms = model;
    }

    private void initDiseaseTable(List<Symptom> symptoms) {
        initSymptomModel(symptoms);
        String[] defaultColumns = {"Symptom ID", "Symptom", "Check"};
        DefaultTableModel tableModel = new DefaultTableModel(defaultColumns, 0) {
            @Override
            public Class<?> getColumnClass(int column) {
                switch (column) {
                    case 0:
                        return Integer.class;
                    case 1:
                        return String.class;
                    case 2:
                        return Boolean.class;
                    default:
                        return String.class;
                }
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 2;
            }
        };
        for (SymptomModel s : this.modeledSymptoms) {
            tableModel.addRow(new Object[]{
                s.getId(),
                s.getDescription(),
                s.getSelected()
            });
        }
        jTable2.setModel(tableModel);
        jTable2.setRowHeight(25);
        DefaultTableCellRenderer centrado = new DefaultTableCellRenderer();
        centrado.setHorizontalAlignment(SwingConstants.CENTER);
        jTable2.getColumnModel().getColumn(0).setCellRenderer(centrado);
        jTable2.getColumnModel().getColumn(0).setPreferredWidth(125);
        jTable2.getColumnModel().getColumn(1).setPreferredWidth(225);
        jTable2.getColumnModel().getColumn(2). setPreferredWidth(100);
    }

    /**
     * Creates new form DiagnosticFrame
     */
    public SymptomSelectionFrame(List<Symptom> symptoms, SpecialistController controller) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        initDiseaseTable(symptoms);
        this.controller = controller;
    }
    public void cleanSymptomListCheck(){
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        for(int i = 0; i < model.getRowCount(); i++){
            model.setValueAt(false, i, 2);
        }
    }

    public JPanel getGenerateDiagnoseButton() {
        return generateDiagnoseButton;
    }

    public JTextField getCampoEdad() {
        return campoEdad;
    }

    public JTextField getCampoNombre() {
        return campoNombre;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        campoEdad = new javax.swing.JTextField();
        campoNombre = new javax.swing.JTextField();
        generateDiagnoseButton = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cleanSymptomButton = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setPreferredSize(new java.awt.Dimension(456, 600));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 450, -1));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Edad");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("INFORMACIÓN DEL PACIENTE");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Nombre");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        campoEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEdadActionPerformed(evt);
            }
        });
        jPanel1.add(campoEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 500, 40));

        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });
        jPanel1.add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 500, 40));

        generateDiagnoseButton.setBackground(new java.awt.Color(102, 255, 51));
        generateDiagnoseButton.setForeground(new java.awt.Color(102, 255, 51));
        generateDiagnoseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        generateDiagnoseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generateDiagnoseButtonMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/donpedromz/integracion_prolog/assets/icons/ok_icon.png"))); // NOI18N

        javax.swing.GroupLayout generateDiagnoseButtonLayout = new javax.swing.GroupLayout(generateDiagnoseButton);
        generateDiagnoseButton.setLayout(generateDiagnoseButtonLayout);
        generateDiagnoseButtonLayout.setHorizontalGroup(
            generateDiagnoseButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        generateDiagnoseButtonLayout.setVerticalGroup(
            generateDiagnoseButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(generateDiagnoseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 550, 10));

        jPanel4.setBackground(new java.awt.Color(102, 153, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("POR FAVOR SELECCIONE LOS SINTOMAS PRESENTADOS");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("¡Se pueden seleccionar uno o más Sintomas!");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 100));

        cleanSymptomButton.setBackground(new java.awt.Color(255, 51, 51));
        cleanSymptomButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cleanSymptomButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cleanSymptomButtonMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/donpedromz/integracion_prolog/assets/icons/delete_icon.png"))); // NOI18N

        javax.swing.GroupLayout cleanSymptomButtonLayout = new javax.swing.GroupLayout(cleanSymptomButton);
        cleanSymptomButton.setLayout(cleanSymptomButtonLayout);
        cleanSymptomButtonLayout.setHorizontalGroup(
            cleanSymptomButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cleanSymptomButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );
        cleanSymptomButtonLayout.setVerticalGroup(
            cleanSymptomButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cleanSymptomButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        jPanel1.add(cleanSymptomButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 128, 128));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEdadActionPerformed

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed

    private void cleanSymptomButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cleanSymptomButtonMouseClicked


        this.cleanSymptomListCheck();
    }//GEN-LAST:event_cleanSymptomButtonMouseClicked

    private void generateDiagnoseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generateDiagnoseButtonMouseClicked

        this.controller.handleClick(evt);
    }//GEN-LAST:event_generateDiagnoseButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoEdad;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JPanel cleanSymptomButton;
    private javax.swing.JPanel generateDiagnoseButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

    public List<Symptom> getSelectedSymptoms() {
        List<Symptom> seleccionados = new ArrayList<>(); 
        DefaultTableModel tableModel = (DefaultTableModel) this.jTable2.getModel();
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            Boolean checked = (Boolean) tableModel.getValueAt(i, 2);
            if (checked) {
                SymptomModel s = modeledSymptoms.get(i);
                s.setSelected(true);
                seleccionados.add(modeledSymptoms.get(i).toSymptom(s));
            }
        }
        return seleccionados;
    }

    /**
     * Muestra los diagnósticos en la tabla reemplazando el modelo actual.
     */
    public void showDiagnostics(List<Diagnostic> diagnostics, List<Symptom> inputSymptoms) {
        this.currentDiagnostics = diagnostics;
        this.currentInputSymptoms = inputSymptoms;

        String[] cols = {"Id", "Enfermedad", "Categoria", "Sintomas", "Recomendaciones", "Sintomas ingresados"};
        DefaultTableModel model = new DefaultTableModel(cols, 0) {
            @Override
            public boolean isCellEditable(int row, int column) { return false; }
        };

        for (Diagnostic d : diagnostics) {
            String sintomasEnfermedad = joinSymptoms(d.getDisease().getSymptoms());
            String recomendaciones = joinRecs(d.getDisease().getRecomendations());
            String sintomasIngresados = joinSymptoms(inputSymptoms);
            model.addRow(new Object[]{
                d.getDisease().getId(),
                d.getDisease().getName(),
                d.getDisease().getCategory() != null ? d.getDisease().getCategory().getName() : "",
                sintomasEnfermedad,
                recomendaciones,
                sintomasIngresados
            });
        }

        jTable2.setModel(model);
        jTable2.setRowHeight(25);
    }

    private String joinSymptoms(List<Symptom> symptoms) {
        if (symptoms == null) return "";
        return symptoms.stream()
                .map(Symptom::getDescription)
                .reduce("", (a, b) -> a.isEmpty() ? b : a + ", " + b);
    }

    private String joinRecs(List<Recomendation> recs) {
        if (recs == null) return "";
        return recs.stream()
                .map(Recomendation::getDescription)
                .reduce("", (a, b) -> a.isEmpty() ? b : a + ", " + b);
    }
}
